export const ROUTES = {
  home: "/",
  onboarding: "/auth/onboarding",
  auth: "/auth",
  login: "/auth/login",
  signup: "/auth/signup",
  forgotPassword: "/auth/forgot-password",
  emailSent: "/auth/email-sent",
  otp: "/auth/otp",
  setup: "/auth/setup",
  updatePassword: "/auth/update-password",
  passwordUpdated: "/auth/password-updated",
  app: {
    main: "/app",
    library: "/app/library",
    search: "/app/search",
    pen: "/app/pen",
    profile: "/app/profile",
    notification: "/app/notification",
    settings: "/app/settings",
    appSetup: "/app/setup",
    allGenres: "/app/all-genres",
    category: "/app/category",
  },
  story: {
    view: "/story/[id]",
    read: "/story/[id]/read",
  },
  editStory: "/edit-story/[id]",
  newStory: "/new-story",
  myStories: "/my-stories",
  premium: "/premium",
  test: "/test",
};

export const NAVIGATION_CONFIG = {
  defaultRoute: ROUTES.onboarding,
  authRequiredRoutes: [
    ROUTES.app.main,
    ROUTES.app.library,
    ROUTES.app.search,
    ROUTES.app.pen,
    ROUTES.app.profile,
    ROUTES.app.notification,
    ROUTES.app.settings,
    ROUTES.editStory,
    ROUTES.newStory,
    ROUTES.myStories,
  ],
  guestOnlyRoutes: [
    ROUTES.auth,
    ROUTES.login,
    ROUTES.signup,
    ROUTES.forgotPassword,
    ROUTES.emailSent,
    ROUTES.otp,
    ROUTES.setup,
    ROUTES.updatePassword,
    ROUTES.passwordUpdated,
    ROUTES.onboarding,
  ],
};
