export const ROUTES = {
  home: "/home",
  onboarding: "/auth/onboarding",
  auth: "/auth",
  login: "/auth/login",
  signup: "/auth/signup",
  forgotPassword: "/auth/forgot-password",
  emailSent: "/auth/email-sent",
  otp: "/auth/otp",
  setup: "/auth/setup",
  updatePassword: "/auth/update-password",
  passwordUpdated: "/auth/password-updated",
  app: {
    main: "/home",
    library: "/library",
    search: "/search",
    pen: "/pen",
    profile: "/profile",
    notification: "/notification",
    settings: "/settings",
    appSetup: "/setup",
    allGenres: "/all-genres",
    category: "/category",
  },
  /** Desktop dashboard routes (/app/*) — separate shell, shared hooks */
  desktop: {
    home: "/app/home",
    library: "/app/library",
    write: "/app/write",
    notifications: "/app/notifications",
    profile: "/app/profile",
    settings: "/app/settings",
    search: "/app/search",
    premium: "/app/premium",
    ambassador: "/app/ambassador",
    newStory: "/app/stories/new",
    myStories: "/app/my-stories",
  },
  story: {
    view: "/story/[id]",
    read: "/story/[id]/read",
  },
  editStory: "/edit-story/[id]",
  newStory: "/new-story",
  myStories: "/my-stories",
  premium: "/premium",
  ambassador: "/ambassador",
  test: "/test",
};

export const NAVIGATION_CONFIG = {
  defaultRoute: ROUTES.onboarding,
  authRequiredRoutes: [
    ROUTES.app.main,
    ROUTES.app.library,
    ROUTES.app.search,
    ROUTES.app.pen,
    ROUTES.app.profile,
    ROUTES.app.notification,
    ROUTES.app.settings,
    ROUTES.editStory,
    ROUTES.newStory,
    ROUTES.myStories,
    ROUTES.premium,
    ROUTES.ambassador,
    ROUTES.desktop.home,
    ROUTES.desktop.library,
    ROUTES.desktop.write,
    ROUTES.desktop.notifications,
    ROUTES.desktop.profile,
    ROUTES.desktop.settings,
    ROUTES.desktop.search,
    ROUTES.desktop.premium,
    ROUTES.desktop.ambassador,
    ROUTES.desktop.newStory,
    ROUTES.desktop.myStories,
  ],
  guestOnlyRoutes: [
    ROUTES.auth,
    ROUTES.login,
    ROUTES.signup,
    ROUTES.forgotPassword,
    ROUTES.emailSent,
    ROUTES.otp,
    ROUTES.setup,
    ROUTES.updatePassword,
    ROUTES.passwordUpdated,
    ROUTES.onboarding,
  ],
};
