export const ROUTES = {
  home: "/",
  onboarding: "/auth/onboarding",
  auth: "/auth",
  login: "/auth/login",
  signup: "/auth/signup",
  forgotPassword: "/auth/forgot-password",
  emailSent: "/auth/email-sent",
  otp: "/auth/otp",
  setup: "/auth/setup",
  updatePassword: "/auth/update-password",
  passwordUpdated: "/auth/password-updated",
  app: {
    main: "/home",
    library: "/library",
    search: "/search",
    pen: "/pen",
    profile: "/profile",
    notification: "/notification",
    settings: "/settings",
    appSetup: "/setup",
    allGenres: "/all-genres",
    category: "/category",
  },
  story: {
    view: "/story/[id]",
    read: "/story/[id]/read",
  },
  editStory: "/edit-story/[id]",
  newStory: "/new-story",
  myStories: "/my-stories",
  premium: "/premium",
  test: "/test",
};

export const NAVIGATION_CONFIG = {
  defaultRoute: ROUTES.onboarding,
  authRequiredRoutes: [
    ROUTES.app.main,
    ROUTES.app.library,
    ROUTES.app.search,
    ROUTES.app.pen,
    ROUTES.app.profile,
    ROUTES.app.notification,
    ROUTES.app.settings,
    ROUTES.editStory,
    ROUTES.newStory,
    ROUTES.myStories,
  ],
  guestOnlyRoutes: [
    ROUTES.auth,
    ROUTES.login,
    ROUTES.signup,
    ROUTES.forgotPassword,
    ROUTES.emailSent,
    ROUTES.otp,
    ROUTES.setup,
    ROUTES.updatePassword,
    ROUTES.passwordUpdated,
    ROUTES.onboarding,
  ],
};
