/**
 * App Config (mobile billing mode) client.
 *
 * This file exists as a stable shim because the typed SDK functions
 * (`appConfigControllerGetConfig`, `appConfigControllerUpdateConfig`) are
 * generated by `@hey-api/openapi-ts` from the live backend's Swagger
 * document, and that document won't include the new endpoints until the
 * backend is deployed and the SDK is regenerated.
 *
 * Once the backend is deployed, run:
 *   pnpm generate:client
 * and the generated functions will appear in `src/client/sdk.gen.ts`. The
 * exported names this file uses (`getAppConfig`, `updateAppConfig`) match
 * the convention the generator produces, so the swap is a one-line change:
 * just replace the `client.get(...)` body with the generated function.
 *
 * In the meantime, calls go through the shared `client` instance so they
 * inherit the same auth, baseURL, retry, and offline behavior as the rest
 * of the app.
 */
import { client } from "./client/client.gen";

export type AppBillingMode = "reader" | "playbilling";

export interface AppConfigDto {
  id: string;
  mode: AppBillingMode;
  force: boolean;
  updatedAt: string;
}

export interface UpdateAppConfigInput {
  mode: AppBillingMode;
  force?: boolean;
}

/**
 * GET /app-config
 * Public — no auth required. Safe to call from the mobile app on every
 * launch and on a 5-minute SWR interval.
 */
export async function getAppConfig(): Promise<AppConfigDto> {
  const res = await client.get({
    url: "/app-config",
  });
  // Hey-API returns `data` as the parsed JSON body. The Nest controller
  // returns the DTO directly (not wrapped in `{ data, statusCode }`),
  // matching the style of the FAQs/terms endpoints.
  return res.data as AppConfigDto;
}

/**
 * PUT /app-config (admin only)
 * Called from the admin dashboard, not from the mobile app.
 */
export async function updateAppConfig(
  input: UpdateAppConfigInput,
): Promise<AppConfigDto> {
  const res = await client.put({
    url: "/app-config",
    body: input,
  });
  return res.data as AppConfigDto;
}
