// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type UpdateProfileDto = {
    /**
     * First name
     */
    firstName?: string;
    /**
     * Last name
     */
    lastName?: string;
    /**
     * Pen name or author name
     */
    penName?: string;
    /**
     * Avatar URL
     */
    avatar?: string;
    /**
     * Profile picture URL
     */
    profilePicture?: string;
    /**
     * Short biography
     */
    bio?: string;
    /**
     * Preferred genres
     */
    genres?: Array<string>;
    /**
     * Preferred time to read
     */
    timeToRead?: string;
    /**
     * Preferred time to write
     */
    timeToWrite?: string;
    /**
     * Reminder schedule
     */
    reminder?: string;
};

export type UpdateReadingProgressDto = {
    /**
     * Percentage of story read (0-100)
     */
    percentageRead?: number;
    /**
     * Number of words read
     */
    wordsRead?: number;
    /**
     * Total words in the story
     */
    totalWords?: number;
    /**
     * Last chapter number read (for stories with chapters)
     */
    lastReadChapter?: number;
    /**
     * Last episode number read (for stories with episodes)
     */
    lastReadEpisode?: number;
    /**
     * Additional reading time in seconds
     */
    readingTimeSeconds?: number;
};

export type SetupProfileDto = {
    /**
     * Pen name or author name
     */
    penName?: string;
    /**
     * Profile picture URL
     */
    profilePicture?: string;
    /**
     * List of genres the user is interested in
     */
    genres?: Array<string>;
    /**
     * Preferred time to read (e.g., "12:00 pm", "1:00 am", "12:00pm", "09:00", "14:30")
     */
    timeToRead?: string;
    /**
     * Preferred time to write (e.g., "12:00 pm", "1:00 am", "12:00pm", "09:00", "14:30")
     */
    timeToWrite?: string;
    /**
     * Reminder schedule (e.g., "monday", "mon-fri", "daily", "weekends")
     */
    reminder?: string;
};

export type RegisterDto = {
    /**
     * User first name
     */
    firstName: string;
    /**
     * User last name
     */
    lastName: string;
    /**
     * User email address
     */
    email: string;
    /**
     * User password (minimum 6 characters)
     */
    password: string;
    /**
     * User date of birth
     */
    dateOfBirth: string;
    /**
     * User agreement to terms and conditions
     */
    agreement: boolean;
};

export type RegisterResponseDto = {
    /**
     * User ID
     */
    id: string;
    /**
     * User first name
     */
    firstName: string;
    /**
     * User last name
     */
    lastName: string;
    /**
     * User email address
     */
    email: string;
    /**
     * User date of birth
     */
    dateOfBirth: string;
    /**
     * User agreement to terms and conditions
     */
    agreement: boolean;
    /**
     * Author ID - assigned automatically when user is created
     */
    authorId: string;
    /**
     * Reader ID - assigned automatically when user is created
     */
    readerId: string;
    /**
     * Account creation timestamp
     */
    createdAt: string;
};

export type VerifyEmailDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * 6-digit OTP code received via email
     */
    otp: string;
};

export type ResendOtpDto = {
    /**
     * User email address
     */
    email: string;
};

export type ForgotPasswordDto = {
    /**
     * User email address
     */
    email: string;
};

export type ResetPasswordDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * 6-digit OTP code received via email
     */
    otp: string;
    /**
     * New password (minimum 8 characters, must contain at least one letter and one number)
     */
    newPassword: string;
};

export type LoginDto = {
    /**
     * User email address or pen name
     */
    emailOrPenName: string;
    /**
     * User password
     */
    password: string;
};

export type AuthResponseDto = {
    /**
     * JWT access token
     */
    accessToken: string;
    /**
     * JWT refresh token
     */
    refreshToken: string;
};

export type RefreshTokenDto = {
    /**
     * Refresh token to validate and exchange for new access token
     */
    refreshToken: string;
};

export type AuthorDto = {
    /**
     * User ID
     */
    id: string;
    /**
     * User email
     */
    email: string;
    /**
     * User name
     */
    name: string;
    /**
     * User avatar URL
     */
    avatar?: string;
    /**
     * Account creation date
     */
    createdAt: string;
};

export type StoryResponseDto = {
    /**
     * Story ID
     */
    id: string;
    /**
     * Story title
     */
    title: string;
    /**
     * Story content
     */
    content: string;
    /**
     * Story genres
     */
    genres?: Array<string>;
    /**
     * Story author
     */
    author: AuthorDto;
    /**
     * Story image URL
     */
    imageUrl?: string;
    /**
     * Story creation date
     */
    createdAt: string;
    /**
     * Story last update date
     */
    updatedAt: string;
};

export type StoriesListResponseDto = {
    /**
     * List of stories
     */
    stories: Array<StoryResponseDto>;
    /**
     * Total number of stories
     */
    total: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of items per page
     */
    limit: number;
    /**
     * Total number of pages
     */
    totalPages: number;
};

export type CreateStoryDto = {
    /**
     * The UUID of the user who is creating the story (author)
     */
    authorId: string;
    /**
     * The title of the story
     */
    title: string;
    /**
     * Short description of the story (50-100 words)
     */
    description: string;
    /**
     * The main content/body of the story
     */
    content: string;
    /**
     * Array of genres to categorize the story
     */
    genres: Array<string>;
    /**
     * Array of pen names of collaborators (optional)
     */
    collaborate?: Array<string>;
    /**
     * Language of the story
     */
    language: 'english' | 'spanish' | 'french' | 'german' | 'italian' | 'portuguese' | 'chinese' | 'japanese' | 'korean' | 'arabic' | 'hindi' | 'russian' | 'other';
    /**
     * If true, author details will not be shown when displaying the story
     */
    anonymous: boolean;
    /**
     * If true, the story can only be published on Storytime and nowhere else
     */
    onlyOnStorytime: boolean;
    /**
     * If true, the story contains 18+ content (trigger warning)
     */
    trigger: boolean;
    /**
     * If true, the user is granting copyright to Storytime
     */
    copyright: boolean;
    /**
     * Status of the story: complete (completed/published), ongoing (chapters/episodes), or drafts (not visible to others except admin and owner)
     */
    storyStatus: 'complete' | 'ongoing' | 'drafts';
    /**
     * If true, the story has chapters
     */
    chapter: boolean;
    /**
     * If true, the story has episodes
     */
    episodes: boolean;
    /**
     * URL to an image associated with the story
     */
    imageUrl?: string;
};

export type UpdateStoryDto = {
    /**
     * Story title
     */
    title?: string;
    /**
     * Story content
     */
    content?: string;
    /**
     * Story genres
     */
    genres?: Array<string>;
    /**
     * Story image URL
     */
    imageUrl?: string;
    /**
     * Array of pen names of collaborators
     */
    collaborate?: Array<string>;
};

export type CreateChapterDto = {
    /**
     * The UUID of the story this chapter belongs to
     */
    storyId: string;
    /**
     * The title of the chapter
     */
    title: string;
    /**
     * The content of the chapter
     */
    content: string;
    /**
     * Chapter number (auto-incremented if not provided)
     */
    chapterNumber?: number;
};

export type CreateMultipleChaptersDto = {
    /**
     * The UUID of the story these chapters belong to
     */
    storyId: string;
    /**
     * Array of chapters to create
     */
    chapters: Array<CreateChapterDto>;
};

export type CreateEpisodeDto = {
    /**
     * The UUID of the story this episode belongs to
     */
    storyId: string;
    /**
     * The title of the episode
     */
    title: string;
    /**
     * The content of the episode
     */
    content: string;
    /**
     * Episode number (auto-incremented if not provided)
     */
    episodeNumber?: number;
};

export type CreateMultipleEpisodesDto = {
    /**
     * The UUID of the story these episodes belong to
     */
    storyId: string;
    /**
     * Array of episodes to create
     */
    episodes: Array<CreateEpisodeDto>;
};

export type CreateCommentDto = {
    /**
     * The UUID of the story to comment on
     */
    storyId: string;
    /**
     * The comment content
     */
    content: string;
};

export type UpdateCommentDto = {
    /**
     * The updated comment content
     */
    content: string;
};

export type AdminLoginDto = {
    /**
     * Admin email address
     */
    email: string;
    /**
     * Admin password
     */
    password: string;
};

export type CreateAdminDto = {
    /**
     * Admin first name
     */
    firstName: string;
    /**
     * Admin last name
     */
    lastName: string;
    /**
     * Admin email address
     */
    email: string;
    /**
     * Admin password (minimum 8 characters)
     */
    password: string;
    /**
     * Admin role
     */
    role: 'super_admin' | 'admin' | 'marketing' | 'developer' | 'designer' | 'finance';
};

export type AdminResponseDto = {
    /**
     * Admin ID
     */
    id: string;
    /**
     * Admin first name
     */
    firstName: string;
    /**
     * Admin last name
     */
    lastName: string;
    /**
     * Admin email address
     */
    email: string;
    /**
     * Admin role
     */
    role: 'super_admin' | 'admin' | 'marketing' | 'developer' | 'designer' | 'finance';
    /**
     * Whether admin is suspended
     */
    isSuspended: boolean;
    /**
     * Suspension timestamp
     */
    suspendedAt: string | null;
    /**
     * ID of admin who suspended this admin
     */
    suspendedBy: string | null;
    /**
     * Last login timestamp
     */
    lastLoginAt: string | null;
    /**
     * Account creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
};

export type UpdateAdminDto = {
    /**
     * Admin first name
     */
    firstName?: string;
    /**
     * Admin last name
     */
    lastName?: string;
    /**
     * Admin email address
     */
    email?: string;
    /**
     * Admin role
     */
    role?: 'super_admin' | 'admin' | 'marketing' | 'developer' | 'designer' | 'finance';
};

export type CreateNotificationDto = {
    /**
     * Notification title
     */
    title: string;
    /**
     * Notification message/content
     */
    message: string;
    /**
     * Type of notification
     */
    type: 'achievement' | 'milestone' | 'admin_message' | 'reminder_read' | 'reminder_write' | 'story_like' | 'story_comment' | 'story_collaboration' | 'system';
    /**
     * The UUID of the user to send the notification to (required if email is not provided)
     */
    userId?: string;
    /**
     * The email of the user to send the notification to (required if userId is not provided)
     */
    email?: string;
    /**
     * Additional metadata (JSON object)
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * Whether to send email notification
     */
    sendEmail?: boolean;
};

export type CreateBulkNotificationDto = {
    /**
     * Notification title
     */
    title: string;
    /**
     * Notification message/content
     */
    message: string;
    /**
     * Type of notification
     */
    type: 'achievement' | 'milestone' | 'admin_message' | 'reminder_read' | 'reminder_write' | 'story_like' | 'story_comment' | 'story_collaboration' | 'system';
    /**
     * Additional metadata (JSON object)
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * Whether to send email notification to all users
     */
    sendEmail?: boolean;
    /**
     * Optional list of user emails to send notification to (if not provided, sends to all users)
     */
    emails?: Array<string>;
    /**
     * Optional list of user IDs to send notification to (if not provided, sends to all users)
     */
    userIds?: Array<string>;
};

export type UsersControllerCheckPenNameAvailabilityData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The pen name to check for availability
         */
        penName: string;
    };
    url: '/users/pen-name/check';
};

export type UsersControllerCheckPenNameAvailabilityErrors = {
    /**
     * Invalid pen name provided
     */
    400: unknown;
};

export type UsersControllerCheckPenNameAvailabilityResponses = {
    /**
     * Pen name availability check completed
     */
    200: {
        available?: boolean;
        penName?: string;
        message?: string;
    };
};

export type UsersControllerCheckPenNameAvailabilityResponse = UsersControllerCheckPenNameAvailabilityResponses[keyof UsersControllerCheckPenNameAvailabilityResponses];

export type UsersControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/profile';
};

export type UsersControllerGetProfileErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type UsersControllerGetProfileResponses = {
    /**
     * User profile retrieved successfully
     */
    200: {
        message?: string;
        user?: {
            id?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            penName?: string | null;
            profilePicture?: string | null;
            genres?: Array<string> | null;
            timeToRead?: string | null;
            timeToWrite?: string | null;
            reminder?: string | null;
            /**
             * Indicates whether the user has completed profile setup via POST /users/profile/setup. Returns true if penName is set or at least 2 setup fields are filled.
             */
            isSetupComplete?: boolean;
            stats?: {
                storiesRead?: number;
                storiesWritten?: number;
                badgesCount?: number;
                certificatesCount?: number;
            };
        };
    };
};

export type UsersControllerGetProfileResponse = UsersControllerGetProfileResponses[keyof UsersControllerGetProfileResponses];

export type UsersControllerUpdateProfileData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/users/profile';
};

export type UsersControllerUpdateProfileErrors = {
    /**
     * Validation error or pen name already taken
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type UsersControllerUpdateProfileResponses = {
    /**
     * Profile updated successfully
     */
    200: unknown;
};

export type UsersControllerMarkStoryAsReadData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/users/stories/{id}/read';
};

export type UsersControllerMarkStoryAsReadErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type UsersControllerMarkStoryAsReadResponses = {
    /**
     * Story marked as read successfully
     */
    200: {
        message?: string;
        storyRead?: {
            [key: string]: unknown;
        };
        badgesAwarded?: Array<string>;
    };
};

export type UsersControllerMarkStoryAsReadResponse = UsersControllerMarkStoryAsReadResponses[keyof UsersControllerMarkStoryAsReadResponses];

export type UsersControllerGetReadingHistoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 20, max: 100)
         */
        limit?: number;
    };
    url: '/users/reading-history';
};

export type UsersControllerGetReadingHistoryErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type UsersControllerGetReadingHistoryResponses = {
    /**
     * Reading history retrieved successfully
     */
    200: unknown;
};

export type UsersControllerGetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/stats';
};

export type UsersControllerGetStatsErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type UsersControllerGetStatsResponses = {
    /**
     * User statistics retrieved successfully
     */
    200: unknown;
};

export type UsersControllerGetReadingProgressData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/users/stories/{id}/progress';
};

export type UsersControllerGetReadingProgressErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type UsersControllerGetReadingProgressResponses = {
    /**
     * Reading progress retrieved successfully
     */
    200: unknown;
};

export type UsersControllerUpdateReadingProgressData = {
    body: UpdateReadingProgressDto;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/users/stories/{id}/progress';
};

export type UsersControllerUpdateReadingProgressErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type UsersControllerUpdateReadingProgressResponses = {
    /**
     * Reading progress updated successfully. Returns progress data and whether the story was marked as read.
     */
    200: {
        message?: string;
        progress?: {
            [key: string]: unknown;
        };
        /**
         * Whether the story was marked as read
         */
        markedAsRead?: boolean;
        /**
         * Reason for marking as read (time_based_300s or progress_100_percent)
         */
        reason?: string;
    };
};

export type UsersControllerUpdateReadingProgressResponse = UsersControllerUpdateReadingProgressResponses[keyof UsersControllerUpdateReadingProgressResponses];

export type UsersControllerGetAllReadingProgressData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 20, max: 100)
         */
        limit?: number;
    };
    url: '/users/reading-progress';
};

export type UsersControllerGetAllReadingProgressErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type UsersControllerGetAllReadingProgressResponses = {
    /**
     * Reading progress list retrieved successfully
     */
    200: unknown;
};

export type UsersControllerGetShareableAchievementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/achievements/share';
};

export type UsersControllerGetShareableAchievementsErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type UsersControllerGetShareableAchievementsResponses = {
    /**
     * Achievement data retrieved successfully
     */
    200: unknown;
};

export type UsersControllerGetTopReadersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of top readers to return (default: 10, max: 100)
         */
        limit?: number;
    };
    url: '/users/leaderboard/readers';
};

export type UsersControllerGetTopReadersResponses = {
    /**
     * Leaderboard retrieved successfully
     */
    200: unknown;
};

export type UsersControllerGetTopAuthorsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of top authors to return (default: 10, max: 100)
         */
        limit?: number;
    };
    url: '/users/leaderboard/authors';
};

export type UsersControllerGetTopAuthorsResponses = {
    /**
     * Leaderboard retrieved successfully
     */
    200: unknown;
};

export type UsersControllerGetTopReadersByTimeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of top readers to return (default: 10, max: 100)
         */
        limit?: number;
    };
    url: '/users/leaderboard/reading-time';
};

export type UsersControllerGetTopReadersByTimeResponses = {
    /**
     * Leaderboard retrieved successfully
     */
    200: unknown;
};

export type UsersControllerGetTopBadgeHoldersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of top users to return (default: 10, max: 100)
         */
        limit?: number;
    };
    url: '/users/leaderboard/badges';
};

export type UsersControllerGetTopBadgeHoldersResponses = {
    /**
     * Leaderboard retrieved successfully
     */
    200: unknown;
};

export type UsersControllerGetTopCertificateHoldersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of top users to return (default: 10, max: 100)
         */
        limit?: number;
    };
    url: '/users/leaderboard/certificates';
};

export type UsersControllerGetTopCertificateHoldersResponses = {
    /**
     * Leaderboard retrieved successfully
     */
    200: unknown;
};

export type UsersControllerSetupProfileData = {
    body: SetupProfileDto;
    path?: never;
    query?: never;
    url: '/users/profile/setup';
};

export type UsersControllerSetupProfileErrors = {
    /**
     * Email not verified, validation error, empty pen name, or account is suspended/deleted
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
    /**
     * Pen name is already taken by another user
     */
    409: unknown;
};

export type UsersControllerSetupProfileResponses = {
    /**
     * Profile setup completed successfully
     */
    200: {
        message?: string;
        user?: {
            id?: string;
            email?: string;
            penName?: string;
            profilePicture?: string;
            genres?: Array<string>;
            timeToRead?: string;
            timeToWrite?: string;
            reminder?: string;
        };
    };
};

export type UsersControllerSetupProfileResponse = UsersControllerSetupProfileResponses[keyof UsersControllerSetupProfileResponses];

export type UsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersControllerFindAllResponses = {
    /**
     * List of all users
     */
    200: unknown;
};

export type UsersControllerDeleteUserData = {
    body?: never;
    path: {
        /**
         * User UUID to delete
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerDeleteUserErrors = {
    /**
     * User is already deleted
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type UsersControllerDeleteUserResponses = {
    /**
     * User deleted successfully
     */
    200: unknown;
};

export type UsersControllerFindOneData = {
    body?: never;
    path: {
        /**
         * User UUID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerFindOneErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type UsersControllerFindOneResponses = {
    /**
     * User found
     */
    200: unknown;
};

export type UsersControllerSuspendUserData = {
    body?: never;
    path: {
        /**
         * User UUID to suspend
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/suspend';
};

export type UsersControllerSuspendUserErrors = {
    /**
     * User is already suspended or deleted
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type UsersControllerSuspendUserResponses = {
    /**
     * User suspended successfully
     */
    200: unknown;
};

export type UsersControllerUnsuspendUserData = {
    body?: never;
    path: {
        /**
         * User UUID to unsuspend
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/unsuspend';
};

export type UsersControllerUnsuspendUserErrors = {
    /**
     * User is not suspended
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type UsersControllerUnsuspendUserResponses = {
    /**
     * User unsuspended successfully
     */
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * User with this email already exists
     */
    409: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * User successfully registered
     */
    201: RegisterResponseDto;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerVerifyEmailData = {
    body: VerifyEmailDto;
    path?: never;
    query?: never;
    url: '/auth/verify-email';
};

export type AuthControllerVerifyEmailErrors = {
    /**
     * Invalid or expired OTP, or email already verified
     */
    400: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type AuthControllerVerifyEmailResponses = {
    /**
     * Email verified successfully and JWT token returned
     */
    200: {
        message?: string;
        access_token?: string;
        user?: {
            id?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            isEmailVerified?: boolean;
        };
    };
};

export type AuthControllerVerifyEmailResponse = AuthControllerVerifyEmailResponses[keyof AuthControllerVerifyEmailResponses];

export type AuthControllerResendOtpData = {
    body: ResendOtpDto;
    path?: never;
    query?: never;
    url: '/auth/resend-otp';
};

export type AuthControllerResendOtpErrors = {
    /**
     * Email already verified or OTP still valid
     */
    400: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type AuthControllerResendOtpResponses = {
    /**
     * OTP resent successfully
     */
    200: unknown;
};

export type AuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthControllerForgotPasswordErrors = {
    /**
     * Validation error or user account is suspended/deleted
     */
    400: unknown;
    /**
     * User not found with this email address
     */
    404: unknown;
};

export type AuthControllerForgotPasswordResponses = {
    /**
     * Password reset OTP sent successfully
     */
    200: {
        statusType?: string;
        statusCode?: number;
        message?: string;
        data?: {
            email?: string;
        };
        timestamp?: string;
        path?: string;
    };
};

export type AuthControllerForgotPasswordResponse = AuthControllerForgotPasswordResponses[keyof AuthControllerForgotPasswordResponses];

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type AuthControllerResetPasswordErrors = {
    /**
     * Invalid or expired OTP, validation error, or account is suspended/deleted
     */
    400: unknown;
    /**
     * User not found with this email address
     */
    404: unknown;
};

export type AuthControllerResetPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: {
        statusType?: string;
        statusCode?: number;
        message?: string;
        data?: {
            email?: string;
        };
        timestamp?: string;
        path?: string;
    };
};

export type AuthControllerResetPasswordResponse = AuthControllerResetPasswordResponses[keyof AuthControllerResetPasswordResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * User successfully logged in
     */
    200: AuthResponseDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRefreshData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Invalid or expired refresh token
     */
    401: unknown;
};

export type AuthControllerRefreshResponses = {
    /**
     * Access token refreshed successfully
     */
    200: AuthResponseDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type AuthControllerLogoutResponses = {
    /**
     * User successfully logged out
     */
    200: {
        message?: string;
        timestamp?: string;
    };
};

export type AuthControllerLogoutResponse = AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type NotificationsControllerGetUserNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 50, max: 100)
         */
        limit?: number;
        /**
         * Filter by read status (true for read, false for unread)
         */
        isRead?: boolean;
        /**
         * Filter by notification type
         */
        type?: 'achievement' | 'milestone' | 'admin_message' | 'reminder_read' | 'reminder_write' | 'story_like' | 'story_comment' | 'story_collaboration' | 'system';
    };
    url: '/notifications';
};

export type NotificationsControllerGetUserNotificationsErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type NotificationsControllerGetUserNotificationsResponses = {
    /**
     * Notifications retrieved successfully
     */
    200: {
        notifications?: Array<{
            [key: string]: unknown;
        }>;
        total?: number;
        page?: number;
        limit?: number;
        totalPages?: number;
        unreadCount?: number;
    };
};

export type NotificationsControllerGetUserNotificationsResponse = NotificationsControllerGetUserNotificationsResponses[keyof NotificationsControllerGetUserNotificationsResponses];

export type NotificationsControllerGetUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/unread/count';
};

export type NotificationsControllerGetUnreadCountErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type NotificationsControllerGetUnreadCountResponses = {
    /**
     * Unread count retrieved successfully
     */
    200: {
        unreadCount?: number;
    };
};

export type NotificationsControllerGetUnreadCountResponse = NotificationsControllerGetUnreadCountResponses[keyof NotificationsControllerGetUnreadCountResponses];

export type NotificationsControllerMarkAsReadData = {
    body?: never;
    path: {
        /**
         * Notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type NotificationsControllerMarkAsReadErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Notification not found
     */
    404: unknown;
};

export type NotificationsControllerMarkAsReadResponses = {
    /**
     * Notification marked as read successfully
     */
    200: unknown;
};

export type NotificationsControllerMarkAllAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/read/all';
};

export type NotificationsControllerMarkAllAsReadErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type NotificationsControllerMarkAllAsReadResponses = {
    /**
     * All notifications marked as read successfully
     */
    200: {
        updated?: number;
    };
};

export type NotificationsControllerMarkAllAsReadResponse = NotificationsControllerMarkAllAsReadResponses[keyof NotificationsControllerMarkAllAsReadResponses];

export type NotificationsControllerDeleteNotificationData = {
    body?: never;
    path: {
        /**
         * Notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/notifications/{id}';
};

export type NotificationsControllerDeleteNotificationErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Notification not found
     */
    404: unknown;
};

export type NotificationsControllerDeleteNotificationResponses = {
    /**
     * Notification deleted successfully
     */
    204: void;
};

export type NotificationsControllerDeleteNotificationResponse = NotificationsControllerDeleteNotificationResponses[keyof NotificationsControllerDeleteNotificationResponses];

export type NotificationsControllerGetNotificationByIdData = {
    body?: never;
    path: {
        /**
         * Notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/notifications/{id}';
};

export type NotificationsControllerGetNotificationByIdErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Notification not found
     */
    404: unknown;
};

export type NotificationsControllerGetNotificationByIdResponses = {
    /**
     * Notification retrieved successfully
     */
    200: {
        id?: string;
        title?: string;
        message?: string;
        type?: 'achievement' | 'milestone' | 'admin_message' | 'reminder_read' | 'reminder_write' | 'story_like' | 'story_comment' | 'system';
        isRead?: boolean;
        readAt?: string | null;
        emailSent?: boolean;
        emailSentAt?: string | null;
        metadata?: {
            [key: string]: unknown;
        } | null;
        createdAt?: string;
        updatedAt?: string;
        sentBy?: {
            id?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
        } | null;
    };
};

export type NotificationsControllerGetNotificationByIdResponse = NotificationsControllerGetNotificationByIdResponses[keyof NotificationsControllerGetNotificationByIdResponses];

export type NotificationsControllerDeleteAllNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/all';
};

export type NotificationsControllerDeleteAllNotificationsErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type NotificationsControllerDeleteAllNotificationsResponses = {
    /**
     * All notifications deleted successfully
     */
    200: {
        deleted?: number;
    };
};

export type NotificationsControllerDeleteAllNotificationsResponse = NotificationsControllerDeleteAllNotificationsResponses[keyof NotificationsControllerDeleteAllNotificationsResponses];

export type SearchCollaboratorsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Pen name or partial pen name to search for (case-insensitive, supports partial matches)
         */
        penName: string;
        /**
         * Maximum number of suggestions to return (default: 10, max: 20)
         */
        limit?: number;
    };
    url: '/stories/collaborators/search';
};

export type SearchCollaboratorsErrors = {
    /**
     * Invalid pen name provided
     */
    400: unknown;
};

export type SearchCollaboratorsResponses = {
    /**
     * Collaborator search completed
     */
    200: {
        searchTerm?: string;
        suggestions?: Array<{
            id?: string;
            penName?: string;
            firstName?: string;
            lastName?: string;
            avatar?: string;
        }>;
        count?: number;
        message?: string;
    };
};

export type SearchCollaboratorsResponse = SearchCollaboratorsResponses[keyof SearchCollaboratorsResponses];

export type SearchStoriesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search query to match against story title, description, content, chapters, episodes, or genres
         */
        query: string;
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 10, max: 100)
         */
        limit?: number;
    };
    url: '/stories/search';
};

export type SearchStoriesErrors = {
    /**
     * Bad request - Search query is required or invalid
     */
    400: unknown;
};

export type SearchStoriesResponses = {
    /**
     * Search results retrieved successfully
     */
    200: {
        stories?: Array<{
            [key: string]: unknown;
        }>;
        total?: number;
        page?: number;
        limit?: number;
        totalPages?: number;
        query?: string;
    };
};

export type SearchStoriesResponse = SearchStoriesResponses[keyof SearchStoriesResponses];

export type StoriesControllerGetGenresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stories/genres';
};

export type StoriesControllerGetGenresResponses = {
    /**
     * Genres retrieved successfully
     */
    200: {
        genres?: Array<string>;
    };
};

export type StoriesControllerGetGenresResponse = StoriesControllerGetGenresResponses[keyof StoriesControllerGetGenresResponses];

export type StoriesControllerTestByGenresData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 10)
         */
        limit?: number;
        /**
         * One or more genres to filter by (e.g., genres=Romance&genres=Drama)
         */
        genres: Array<string>;
    };
    url: '/stories/test-by-genres';
};

export type StoriesControllerTestByGenresResponses = {
    /**
     * Stories filtered by genres
     */
    200: unknown;
};

export type StoriesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 10, max: 100)
         */
        limit?: number;
        /**
         * Filter stories by one or more genres (e.g., genres=Romance&genres=Drama)
         */
        genres?: Array<string>;
    };
    url: '/stories';
};

export type StoriesControllerFindAllResponses = {
    /**
     * Stories retrieved successfully
     */
    200: StoriesListResponseDto;
};

export type StoriesControllerFindAllResponse = StoriesControllerFindAllResponses[keyof StoriesControllerFindAllResponses];

export type StoriesControllerFindPopularData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 10, max: 100)
         */
        limit?: number;
        /**
         * Filter stories by one or more genres (e.g., genres=Romance&genres=Drama)
         */
        genres?: Array<string>;
    };
    url: '/stories/popular';
};

export type StoriesControllerFindPopularResponses = {
    /**
     * Popular stories retrieved successfully
     */
    200: StoriesListResponseDto;
};

export type StoriesControllerFindPopularResponse = StoriesControllerFindPopularResponses[keyof StoriesControllerFindPopularResponses];

export type StoriesControllerFindRecentlyAddedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 10, max: 100)
         */
        limit?: number;
        /**
         * Filter stories by one or more genres (e.g., genres=Romance&genres=Drama)
         */
        genres?: Array<string>;
    };
    url: '/stories/recently-added';
};

export type StoriesControllerFindRecentlyAddedResponses = {
    /**
     * Recently added stories retrieved successfully
     */
    200: StoriesListResponseDto;
};

export type StoriesControllerFindRecentlyAddedResponse = StoriesControllerFindRecentlyAddedResponses[keyof StoriesControllerFindRecentlyAddedResponses];

export type StoriesControllerFindTrendingNowData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 10, max: 100)
         */
        limit?: number;
        /**
         * Filter stories by one or more genres (e.g., genres=Romance&genres=Drama)
         */
        genres?: Array<string>;
    };
    url: '/stories/trending-now';
};

export type StoriesControllerFindTrendingNowResponses = {
    /**
     * Trending stories retrieved successfully
     */
    200: StoriesListResponseDto;
};

export type StoriesControllerFindTrendingNowResponse = StoriesControllerFindTrendingNowResponses[keyof StoriesControllerFindTrendingNowResponses];

export type StoriesControllerFindOnlyOnStorytimeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 10, max: 100)
         */
        limit?: number;
    };
    url: '/stories/only-on-storytime';
};

export type StoriesControllerFindOnlyOnStorytimeResponses = {
    /**
     * Exclusive stories retrieved successfully
     */
    200: StoriesListResponseDto;
};

export type StoriesControllerFindOnlyOnStorytimeResponse = StoriesControllerFindOnlyOnStorytimeResponses[keyof StoriesControllerFindOnlyOnStorytimeResponses];

export type StoriesControllerGetMyLibraryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 10, max: 100)
         */
        limit?: number;
        /**
         * Filter by story status (optional). If not provided, returns all statuses.
         */
        status?: 'complete' | 'ongoing' | 'drafts';
        /**
         * Filter your library by one or more genres
         */
        genres?: Array<string>;
    };
    url: '/stories/library';
};

export type StoriesControllerGetMyLibraryErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
};

export type StoriesControllerGetMyLibraryResponses = {
    /**
     * User library retrieved successfully
     */
    200: {
        stories?: Array<{
            [key: string]: unknown;
        }>;
        total?: number;
        page?: number;
        limit?: number;
        totalPages?: number;
    };
};

export type StoriesControllerGetMyLibraryResponse = StoriesControllerGetMyLibraryResponses[keyof StoriesControllerGetMyLibraryResponses];

export type StoriesControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}';
};

export type StoriesControllerRemoveErrors = {
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerRemoveResponses = {
    /**
     * Story deleted successfully
     */
    204: void;
};

export type StoriesControllerRemoveResponse = StoriesControllerRemoveResponses[keyof StoriesControllerRemoveResponses];

export type StoriesControllerFindOneData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}';
};

export type StoriesControllerFindOneErrors = {
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerFindOneResponses = {
    /**
     * Story retrieved successfully
     */
    200: StoryResponseDto;
};

export type StoriesControllerFindOneResponse = StoriesControllerFindOneResponses[keyof StoriesControllerFindOneResponses];

export type StoriesControllerUpdateData = {
    body: UpdateStoryDto;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}';
};

export type StoriesControllerUpdateErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerUpdateResponses = {
    /**
     * Story updated successfully
     */
    200: StoryResponseDto;
};

export type StoriesControllerUpdateResponse = StoriesControllerUpdateResponses[keyof StoriesControllerUpdateResponses];

export type StoriesControllerCreateData = {
    /**
     * Story creation data with all new fields
     */
    body: CreateStoryDto;
    path?: never;
    query?: never;
    url: '/stories/create';
};

export type StoriesControllerCreateErrors = {
    /**
     * Validation error - Invalid input data or author not found
     */
    400: {
        statusType?: string;
        statusCode?: number;
        message?: string;
        error?: {
            validation?: Array<{
                field?: string;
                message?: string;
            }>;
        };
        timestamp?: string;
        path?: string;
    };
    /**
     * Author not found - The provided author ID does not exist
     */
    404: unknown;
};

export type StoriesControllerCreateError = StoriesControllerCreateErrors[keyof StoriesControllerCreateErrors];

export type StoriesControllerCreateResponses = {
    /**
     * Story created successfully
     */
    201: StoryResponseDto;
};

export type StoriesControllerCreateResponse = StoriesControllerCreateResponses[keyof StoriesControllerCreateResponses];

export type StoriesControllerCreateChapterData = {
    body: CreateChapterDto;
    path?: never;
    query?: never;
    url: '/stories/chapters';
};

export type StoriesControllerCreateChapterErrors = {
    /**
     * Story does not have chapters enabled or validation error
     */
    400: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerCreateChapterResponses = {
    /**
     * Chapter created successfully
     */
    201: unknown;
};

export type StoriesControllerCreateMultipleChaptersData = {
    body: CreateMultipleChaptersDto;
    path?: never;
    query?: never;
    url: '/stories/chapters/multiple';
};

export type StoriesControllerCreateMultipleChaptersErrors = {
    /**
     * Story does not have chapters enabled or validation error
     */
    400: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerCreateMultipleChaptersResponses = {
    /**
     * Chapters created successfully
     */
    201: unknown;
};

export type StoriesControllerGetStoryChaptersData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}/chapters';
};

export type StoriesControllerGetStoryChaptersErrors = {
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerGetStoryChaptersResponses = {
    /**
     * Chapters retrieved successfully
     */
    200: unknown;
};

export type StoriesControllerSoftDeleteChapterData = {
    body?: never;
    path: {
        /**
         * Chapter UUID
         */
        chapterId: string;
    };
    query?: never;
    url: '/stories/chapters/{chapterId}';
};

export type StoriesControllerSoftDeleteChapterErrors = {
    /**
     * Bad request - Chapter is already deleted
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Only the story author can delete chapters
     */
    403: unknown;
    /**
     * Chapter not found
     */
    404: unknown;
};

export type StoriesControllerSoftDeleteChapterResponses = {
    /**
     * Chapter soft deleted successfully
     */
    204: void;
};

export type StoriesControllerSoftDeleteChapterResponse = StoriesControllerSoftDeleteChapterResponses[keyof StoriesControllerSoftDeleteChapterResponses];

export type StoriesControllerGetChapterByIdData = {
    body?: never;
    path: {
        /**
         * Chapter UUID
         */
        chapterId: string;
    };
    query?: never;
    url: '/stories/chapters/{chapterId}';
};

export type StoriesControllerGetChapterByIdErrors = {
    /**
     * Chapter not found
     */
    404: unknown;
};

export type StoriesControllerGetChapterByIdResponses = {
    /**
     * Chapter retrieved successfully
     */
    200: {
        id?: string;
        title?: string;
        content?: string;
        chapterNumber?: number;
        storyId?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type StoriesControllerGetChapterByIdResponse = StoriesControllerGetChapterByIdResponses[keyof StoriesControllerGetChapterByIdResponses];

export type StoriesControllerUpdateChapterData = {
    body: {
        title?: string;
        content?: string;
        chapterNumber?: number;
    };
    path: {
        /**
         * Chapter UUID
         */
        chapterId: string;
    };
    query?: never;
    url: '/stories/chapters/{chapterId}';
};

export type StoriesControllerUpdateChapterErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Only the story author can update chapters
     */
    403: unknown;
    /**
     * Chapter not found
     */
    404: unknown;
};

export type StoriesControllerUpdateChapterResponses = {
    /**
     * Chapter updated successfully
     */
    200: {
        id?: string;
        title?: string;
        content?: string;
        chapterNumber?: number;
        storyId?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type StoriesControllerUpdateChapterResponse = StoriesControllerUpdateChapterResponses[keyof StoriesControllerUpdateChapterResponses];

export type StoriesControllerGetChapterCommentsData = {
    body?: never;
    path: {
        /**
         * Chapter UUID
         */
        chapterId: string;
    };
    query?: never;
    url: '/stories/chapters/{chapterId}/comments';
};

export type StoriesControllerGetChapterCommentsErrors = {
    /**
     * Chapter not found
     */
    404: unknown;
};

export type StoriesControllerGetChapterCommentsResponses = {
    /**
     * Comments retrieved successfully
     */
    200: unknown;
};

export type StoriesControllerCreateChapterCommentData = {
    body?: never;
    path: {
        /**
         * Chapter UUID
         */
        chapterId: string;
    };
    query?: never;
    url: '/stories/chapters/{chapterId}/comments';
};

export type StoriesControllerCreateChapterCommentErrors = {
    /**
     * Bad request - Throttling or validation error
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Chapter not found
     */
    404: unknown;
};

export type StoriesControllerCreateChapterCommentResponses = {
    /**
     * Comment created successfully
     */
    201: unknown;
};

export type StoriesControllerDeleteChapterCommentData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        commentId: string;
    };
    query?: never;
    url: '/stories/chapter-comments/{commentId}';
};

export type StoriesControllerDeleteChapterCommentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - Not comment author
     */
    403: unknown;
    /**
     * Comment not found
     */
    404: unknown;
};

export type StoriesControllerDeleteChapterCommentResponses = {
    /**
     * Comment deleted successfully
     */
    204: void;
};

export type StoriesControllerDeleteChapterCommentResponse = StoriesControllerDeleteChapterCommentResponses[keyof StoriesControllerDeleteChapterCommentResponses];

export type StoriesControllerGetChapterCommentByIdData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        commentId: string;
    };
    query?: never;
    url: '/stories/chapter-comments/{commentId}';
};

export type StoriesControllerGetChapterCommentByIdErrors = {
    /**
     * Comment not found
     */
    404: unknown;
};

export type StoriesControllerGetChapterCommentByIdResponses = {
    /**
     * Comment retrieved successfully
     */
    200: unknown;
};

export type StoriesControllerUpdateChapterCommentData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        commentId: string;
    };
    query?: never;
    url: '/stories/chapter-comments/{commentId}';
};

export type StoriesControllerUpdateChapterCommentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - Not comment author
     */
    403: unknown;
    /**
     * Comment not found
     */
    404: unknown;
};

export type StoriesControllerUpdateChapterCommentResponses = {
    /**
     * Comment updated successfully
     */
    200: unknown;
};

export type StoriesControllerCreateEpisodeData = {
    body: CreateEpisodeDto;
    path?: never;
    query?: never;
    url: '/stories/episodes';
};

export type StoriesControllerCreateEpisodeErrors = {
    /**
     * Story does not have episodes enabled or validation error
     */
    400: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerCreateEpisodeResponses = {
    /**
     * Episode created successfully
     */
    201: unknown;
};

export type StoriesControllerCreateMultipleEpisodesData = {
    body: CreateMultipleEpisodesDto;
    path?: never;
    query?: never;
    url: '/stories/episodes/multiple';
};

export type StoriesControllerCreateMultipleEpisodesErrors = {
    /**
     * Story does not have episodes enabled or validation error
     */
    400: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerCreateMultipleEpisodesResponses = {
    /**
     * Episodes created successfully
     */
    201: unknown;
};

export type StoriesControllerGetStoryEpisodesData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}/episodes';
};

export type StoriesControllerGetStoryEpisodesErrors = {
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerGetStoryEpisodesResponses = {
    /**
     * Episodes retrieved successfully
     */
    200: unknown;
};

export type StoriesControllerSoftDeleteEpisodeData = {
    body?: never;
    path: {
        /**
         * Episode UUID
         */
        episodeId: string;
    };
    query?: never;
    url: '/stories/episodes/{episodeId}';
};

export type StoriesControllerSoftDeleteEpisodeErrors = {
    /**
     * Bad request - Episode is already deleted
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Only the story author can delete episodes
     */
    403: unknown;
    /**
     * Episode not found
     */
    404: unknown;
};

export type StoriesControllerSoftDeleteEpisodeResponses = {
    /**
     * Episode soft deleted successfully
     */
    204: void;
};

export type StoriesControllerSoftDeleteEpisodeResponse = StoriesControllerSoftDeleteEpisodeResponses[keyof StoriesControllerSoftDeleteEpisodeResponses];

export type StoriesControllerGetEpisodeByIdData = {
    body?: never;
    path: {
        /**
         * Episode UUID
         */
        episodeId: string;
    };
    query?: never;
    url: '/stories/episodes/{episodeId}';
};

export type StoriesControllerGetEpisodeByIdErrors = {
    /**
     * Episode not found
     */
    404: unknown;
};

export type StoriesControllerGetEpisodeByIdResponses = {
    /**
     * Episode retrieved successfully
     */
    200: {
        id?: string;
        title?: string;
        content?: string;
        episodeNumber?: number;
        storyId?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type StoriesControllerGetEpisodeByIdResponse = StoriesControllerGetEpisodeByIdResponses[keyof StoriesControllerGetEpisodeByIdResponses];

export type StoriesControllerUpdateEpisodeData = {
    body: {
        title?: string;
        content?: string;
        episodeNumber?: number;
    };
    path: {
        /**
         * Episode UUID
         */
        episodeId: string;
    };
    query?: never;
    url: '/stories/episodes/{episodeId}';
};

export type StoriesControllerUpdateEpisodeErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Only the story author can update episodes
     */
    403: unknown;
    /**
     * Episode not found
     */
    404: unknown;
};

export type StoriesControllerUpdateEpisodeResponses = {
    /**
     * Episode updated successfully
     */
    200: {
        id?: string;
        title?: string;
        content?: string;
        episodeNumber?: number;
        storyId?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type StoriesControllerUpdateEpisodeResponse = StoriesControllerUpdateEpisodeResponses[keyof StoriesControllerUpdateEpisodeResponses];

export type StoriesControllerGetEpisodeCommentsData = {
    body?: never;
    path: {
        /**
         * Episode UUID
         */
        episodeId: string;
    };
    query?: never;
    url: '/stories/episodes/{episodeId}/comments';
};

export type StoriesControllerGetEpisodeCommentsErrors = {
    /**
     * Episode not found
     */
    404: unknown;
};

export type StoriesControllerGetEpisodeCommentsResponses = {
    /**
     * Comments retrieved successfully
     */
    200: unknown;
};

export type StoriesControllerCreateEpisodeCommentData = {
    body?: never;
    path: {
        /**
         * Episode UUID
         */
        episodeId: string;
    };
    query?: never;
    url: '/stories/episodes/{episodeId}/comments';
};

export type StoriesControllerCreateEpisodeCommentErrors = {
    /**
     * Bad request - Throttling or validation error
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Episode not found
     */
    404: unknown;
};

export type StoriesControllerCreateEpisodeCommentResponses = {
    /**
     * Comment created successfully
     */
    201: unknown;
};

export type StoriesControllerDeleteEpisodeCommentData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        commentId: string;
    };
    query?: never;
    url: '/stories/episode-comments/{commentId}';
};

export type StoriesControllerDeleteEpisodeCommentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - Not comment author
     */
    403: unknown;
    /**
     * Comment not found
     */
    404: unknown;
};

export type StoriesControllerDeleteEpisodeCommentResponses = {
    /**
     * Comment deleted successfully
     */
    204: void;
};

export type StoriesControllerDeleteEpisodeCommentResponse = StoriesControllerDeleteEpisodeCommentResponses[keyof StoriesControllerDeleteEpisodeCommentResponses];

export type StoriesControllerGetEpisodeCommentByIdData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        commentId: string;
    };
    query?: never;
    url: '/stories/episode-comments/{commentId}';
};

export type StoriesControllerGetEpisodeCommentByIdErrors = {
    /**
     * Comment not found
     */
    404: unknown;
};

export type StoriesControllerGetEpisodeCommentByIdResponses = {
    /**
     * Comment retrieved successfully
     */
    200: unknown;
};

export type StoriesControllerUpdateEpisodeCommentData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        commentId: string;
    };
    query?: never;
    url: '/stories/episode-comments/{commentId}';
};

export type StoriesControllerUpdateEpisodeCommentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - Not comment author
     */
    403: unknown;
    /**
     * Comment not found
     */
    404: unknown;
};

export type StoriesControllerUpdateEpisodeCommentResponses = {
    /**
     * Comment updated successfully
     */
    200: unknown;
};

export type StoriesControllerUnlikeStoryData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}/like';
};

export type StoriesControllerUnlikeStoryErrors = {
    /**
     * Story not liked by this user
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerUnlikeStoryResponses = {
    /**
     * Story unliked successfully
     */
    204: void;
};

export type StoriesControllerUnlikeStoryResponse = StoriesControllerUnlikeStoryResponses[keyof StoriesControllerUnlikeStoryResponses];

export type StoriesControllerLikeStoryData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}/like';
};

export type StoriesControllerLikeStoryErrors = {
    /**
     * Story already liked by this user
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerLikeStoryResponses = {
    /**
     * Story liked successfully
     */
    201: unknown;
};

export type StoriesControllerGetStoryLikesData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}/likes';
};

export type StoriesControllerGetStoryLikesErrors = {
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerGetStoryLikesResponses = {
    /**
     * Likes retrieved successfully
     */
    200: unknown;
};

export type StoriesControllerGetStoryLikeCountData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}/likes/count';
};

export type StoriesControllerGetStoryLikeCountErrors = {
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerGetStoryLikeCountResponses = {
    /**
     * Like count retrieved successfully
     */
    200: {
        storyId?: string;
        likeCount?: number;
    };
};

export type StoriesControllerGetStoryLikeCountResponse = StoriesControllerGetStoryLikeCountResponses[keyof StoriesControllerGetStoryLikeCountResponses];

export type StoriesControllerCheckUserLikeData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}/likes/check';
};

export type StoriesControllerCheckUserLikeErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerCheckUserLikeResponses = {
    /**
     * Like status retrieved successfully
     */
    200: {
        storyId?: string;
        userId?: string;
        hasLiked?: boolean;
    };
};

export type StoriesControllerCheckUserLikeResponse = StoriesControllerCheckUserLikeResponses[keyof StoriesControllerCheckUserLikeResponses];

export type StoriesControllerCreateCommentData = {
    body: CreateCommentDto;
    path?: never;
    query?: never;
    url: '/stories/comments';
};

export type StoriesControllerCreateCommentErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerCreateCommentResponses = {
    /**
     * Comment created successfully
     */
    201: unknown;
};

export type StoriesControllerGetStoryCommentsData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}/comments';
};

export type StoriesControllerGetStoryCommentsErrors = {
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerGetStoryCommentsResponses = {
    /**
     * Comments retrieved successfully
     */
    200: unknown;
};

export type StoriesControllerGetStoryCommentCountData = {
    body?: never;
    path: {
        /**
         * Story UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/{id}/comments/count';
};

export type StoriesControllerGetStoryCommentCountErrors = {
    /**
     * Story not found
     */
    404: unknown;
};

export type StoriesControllerGetStoryCommentCountResponses = {
    /**
     * Comment count retrieved successfully
     */
    200: {
        storyId?: string;
        commentCount?: number;
    };
};

export type StoriesControllerGetStoryCommentCountResponse = StoriesControllerGetStoryCommentCountResponses[keyof StoriesControllerGetStoryCommentCountResponses];

export type StoriesControllerDeleteCommentData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/comments/{id}';
};

export type StoriesControllerDeleteCommentErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - You can only delete your own comments
     */
    403: unknown;
    /**
     * Comment not found
     */
    404: unknown;
};

export type StoriesControllerDeleteCommentResponses = {
    /**
     * Comment deleted successfully
     */
    204: void;
};

export type StoriesControllerDeleteCommentResponse = StoriesControllerDeleteCommentResponses[keyof StoriesControllerDeleteCommentResponses];

export type StoriesControllerUpdateCommentData = {
    body: UpdateCommentDto;
    path: {
        /**
         * Comment UUID
         */
        id: string;
    };
    query?: never;
    url: '/stories/comments/{id}';
};

export type StoriesControllerUpdateCommentErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - You can only update your own comments
     */
    403: unknown;
    /**
     * Comment not found
     */
    404: unknown;
};

export type StoriesControllerUpdateCommentResponses = {
    /**
     * Comment updated successfully
     */
    200: unknown;
};

export type AdminControllerLoginData = {
    body: AdminLoginDto;
    path?: never;
    query?: never;
    url: '/admin/login';
};

export type AdminControllerLoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type AdminControllerLoginResponses = {
    /**
     * Admin successfully logged in
     */
    200: unknown;
};

export type AdminControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin';
};

export type AdminControllerFindAllErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type AdminControllerFindAllResponses = {
    /**
     * List of all admins
     */
    200: unknown;
};

export type AdminControllerCreateData = {
    body: CreateAdminDto;
    path?: never;
    query?: never;
    url: '/admin';
};

export type AdminControllerCreateErrors = {
    /**
     * Forbidden - Super Admin access required
     */
    403: unknown;
    /**
     * Admin with this email already exists
     */
    409: unknown;
};

export type AdminControllerCreateResponses = {
    /**
     * Admin created successfully
     */
    201: AdminResponseDto;
};

export type AdminControllerCreateResponse = AdminControllerCreateResponses[keyof AdminControllerCreateResponses];

export type AdminControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/profile';
};

export type AdminControllerGetProfileErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Admin not found
     */
    404: unknown;
};

export type AdminControllerGetProfileResponses = {
    /**
     * Admin profile retrieved successfully
     */
    200: unknown;
};

export type AdminControllerGetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type AdminControllerGetAllUsersErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
};

export type AdminControllerGetAllUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: unknown;
};

export type AdminControllerGetAllStoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Items per page (default: 10, max: 100)
         */
        limit?: number;
        /**
         * Filter stories by one or more genres
         */
        genres?: Array<string>;
    };
    url: '/admin/stories';
};

export type AdminControllerGetAllStoriesErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
};

export type AdminControllerGetAllStoriesResponses = {
    /**
     * Stories retrieved successfully
     */
    200: unknown;
};

export type AdminControllerDeleteStoryData = {
    body?: never;
    path: {
        /**
         * Story UUID to delete
         */
        id: string;
    };
    query?: never;
    url: '/admin/stories/{id}';
};

export type AdminControllerDeleteStoryErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type AdminControllerDeleteStoryResponses = {
    /**
     * Story deleted successfully
     */
    200: unknown;
};

export type AdminControllerUpdateStoryData = {
    body: UpdateStoryDto;
    path: {
        /**
         * Story UUID to update
         */
        id: string;
    };
    query?: never;
    url: '/admin/stories/{id}';
};

export type AdminControllerUpdateStoryErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type AdminControllerUpdateStoryResponses = {
    /**
     * Story updated successfully
     */
    200: unknown;
};

export type AdminControllerSuspendStoryData = {
    body?: never;
    path: {
        /**
         * Story UUID to suspend
         */
        id: string;
    };
    query?: never;
    url: '/admin/stories/{id}/suspend';
};

export type AdminControllerSuspendStoryErrors = {
    /**
     * Story is already suspended
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type AdminControllerSuspendStoryResponses = {
    /**
     * Story suspended successfully
     */
    200: unknown;
};

export type AdminControllerUnsuspendStoryData = {
    body?: never;
    path: {
        /**
         * Story UUID to unsuspend
         */
        id: string;
    };
    query?: never;
    url: '/admin/stories/{id}/unsuspend';
};

export type AdminControllerUnsuspendStoryErrors = {
    /**
     * Story is not suspended
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
    /**
     * Story not found
     */
    404: unknown;
};

export type AdminControllerUnsuspendStoryResponses = {
    /**
     * Story unsuspended successfully
     */
    200: unknown;
};

export type AdminControllerSuspendUserData = {
    body?: never;
    path: {
        /**
         * User UUID to suspend
         */
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/suspend';
};

export type AdminControllerSuspendUserErrors = {
    /**
     * User is already suspended or deleted
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type AdminControllerSuspendUserResponses = {
    /**
     * User suspended successfully
     */
    200: unknown;
};

export type AdminControllerUnsuspendUserData = {
    body?: never;
    path: {
        /**
         * User UUID to unsuspend
         */
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/unsuspend';
};

export type AdminControllerUnsuspendUserErrors = {
    /**
     * User is not suspended
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type AdminControllerUnsuspendUserResponses = {
    /**
     * User unsuspended successfully
     */
    200: unknown;
};

export type AdminControllerDeleteUserData = {
    body?: never;
    path: {
        /**
         * User UUID to delete
         */
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminControllerDeleteUserErrors = {
    /**
     * User is already deleted
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type AdminControllerDeleteUserResponses = {
    /**
     * User deleted successfully
     */
    200: unknown;
};

export type AdminControllerDeleteAdminData = {
    body?: never;
    path: {
        /**
         * Admin UUID to delete
         */
        id: string;
    };
    query?: never;
    url: '/admin/{id}';
};

export type AdminControllerDeleteAdminErrors = {
    /**
     * Admin is already deleted
     */
    400: unknown;
    /**
     * Forbidden - Super Admin access required
     */
    403: unknown;
    /**
     * Admin not found
     */
    404: unknown;
};

export type AdminControllerDeleteAdminResponses = {
    /**
     * Admin deleted successfully
     */
    200: unknown;
};

export type AdminControllerFindOneData = {
    body?: never;
    path: {
        /**
         * Admin UUID
         */
        id: string;
    };
    query?: never;
    url: '/admin/{id}';
};

export type AdminControllerFindOneErrors = {
    /**
     * Admin not found
     */
    404: unknown;
};

export type AdminControllerFindOneResponses = {
    /**
     * Admin found
     */
    200: unknown;
};

export type AdminControllerUpdateData = {
    body: UpdateAdminDto;
    path: {
        /**
         * Admin UUID
         */
        id: string;
    };
    query?: never;
    url: '/admin/{id}';
};

export type AdminControllerUpdateErrors = {
    /**
     * Forbidden - Super Admin access required
     */
    403: unknown;
    /**
     * Admin not found
     */
    404: unknown;
};

export type AdminControllerUpdateResponses = {
    /**
     * Admin updated successfully
     */
    200: unknown;
};

export type AdminControllerSuspendAdminData = {
    body?: never;
    path: {
        /**
         * Admin UUID to suspend
         */
        id: string;
    };
    query?: never;
    url: '/admin/{id}/suspend';
};

export type AdminControllerSuspendAdminErrors = {
    /**
     * Admin is already suspended or deleted
     */
    400: unknown;
    /**
     * Forbidden - Super Admin access required
     */
    403: unknown;
    /**
     * Admin not found
     */
    404: unknown;
};

export type AdminControllerSuspendAdminResponses = {
    /**
     * Admin suspended successfully
     */
    200: unknown;
};

export type AdminControllerUnsuspendAdminData = {
    body?: never;
    path: {
        /**
         * Admin UUID to unsuspend
         */
        id: string;
    };
    query?: never;
    url: '/admin/{id}/unsuspend';
};

export type AdminControllerUnsuspendAdminErrors = {
    /**
     * Admin is not suspended
     */
    400: unknown;
    /**
     * Forbidden - Super Admin access required
     */
    403: unknown;
    /**
     * Admin not found
     */
    404: unknown;
};

export type AdminControllerUnsuspendAdminResponses = {
    /**
     * Admin unsuspended successfully
     */
    200: unknown;
};

export type AdminControllerSendNotificationData = {
    body: CreateNotificationDto;
    path?: never;
    query?: never;
    url: '/admin/notifications';
};

export type AdminControllerSendNotificationErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type AdminControllerSendNotificationResponses = {
    /**
     * Notification sent successfully
     */
    201: unknown;
};

export type AdminControllerSendBulkNotificationData = {
    body: CreateBulkNotificationDto;
    path?: never;
    query?: never;
    url: '/admin/notifications/bulk';
};

export type AdminControllerSendBulkNotificationErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
};

export type AdminControllerSendBulkNotificationResponses = {
    /**
     * Bulk notification sent successfully
     */
    201: {
        message?: string;
        /**
         * Number of notifications created for registered users
         */
        created?: number;
        /**
         * Number of failed notifications/emails
         */
        failed?: number;
        /**
         * Number of emails sent to external (non-user) addresses
         */
        externalEmailsSent?: number;
    };
};

export type AdminControllerSendBulkNotificationResponse = AdminControllerSendBulkNotificationResponses[keyof AdminControllerSendBulkNotificationResponses];

export type AdminControllerGetAllEpisodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/episodes';
};

export type AdminControllerGetAllEpisodesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
};

export type AdminControllerGetAllEpisodesResponses = {
    /**
     * Episodes retrieved successfully
     */
    200: unknown;
};

export type AdminControllerDeleteEpisodeData = {
    body?: never;
    path: {
        /**
         * Episode UUID
         */
        id: string;
    };
    query?: never;
    url: '/admin/episodes/{id}';
};

export type AdminControllerDeleteEpisodeErrors = {
    /**
     * Episode not found
     */
    404: unknown;
};

export type AdminControllerDeleteEpisodeResponses = {
    /**
     * Episode deleted successfully
     */
    200: unknown;
};

export type AdminControllerGetAllChaptersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/chapters';
};

export type AdminControllerGetAllChaptersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - Admin access required
     */
    403: unknown;
};

export type AdminControllerGetAllChaptersResponses = {
    /**
     * Chapters retrieved successfully
     */
    200: unknown;
};

export type AdminControllerDeleteChapterData = {
    body?: never;
    path: {
        /**
         * Chapter UUID
         */
        id: string;
    };
    query?: never;
    url: '/admin/chapters/{id}';
};

export type AdminControllerDeleteChapterErrors = {
    /**
     * Chapter not found
     */
    404: unknown;
};

export type AdminControllerDeleteChapterResponses = {
    /**
     * Chapter deleted successfully
     */
    200: unknown;
};

export type AdminControllerGetAllCommentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by comment type
         */
        type?: 'story' | 'episode' | 'chapter';
    };
    url: '/admin/comments';
};

export type AdminControllerGetAllCommentsResponses = {
    /**
     * Comments retrieved successfully
     */
    200: unknown;
};

export type AdminControllerDeleteStoryCommentData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        id: string;
    };
    query?: never;
    url: '/admin/comments/story/{id}';
};

export type AdminControllerDeleteStoryCommentResponses = {
    /**
     * Comment deleted successfully
     */
    200: unknown;
};

export type AdminControllerDeleteEpisodeCommentData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        id: string;
    };
    query?: never;
    url: '/admin/comments/episode/{id}';
};

export type AdminControllerDeleteEpisodeCommentResponses = {
    /**
     * Comment deleted successfully
     */
    200: unknown;
};

export type AdminControllerDeleteChapterCommentData = {
    body?: never;
    path: {
        /**
         * Comment UUID
         */
        id: string;
    };
    query?: never;
    url: '/admin/comments/chapter/{id}';
};

export type AdminControllerDeleteChapterCommentResponses = {
    /**
     * Comment deleted successfully
     */
    200: unknown;
};

export type AdminControllerGetOverviewReportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/reports/overview';
};

export type AdminControllerGetOverviewReportResponses = {
    /**
     * Overview report retrieved successfully
     */
    200: unknown;
};
